apiVersion: v1
kind: Service
metadata:
  name: "{{ include "kogger-api.name" . }}"
  labels:
{{ include "kogger-api.labels" . | indent 4 }}
spec:
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.service.port }}
  selector:
{{ include "kogger-api.matchLabels" . | indent 4 }}