swagger: "2.0"
info:
  version: "1.0.0"
  title: "API for kogger"
basePath: "/api"
tags:
  - name: "Logs"
    description: "Endpoints for logs"

paths:
  /namespaces:
    get:
      tags:
        - "Logs"
      summary: "Get all namespaces"
      operationId: "getNamespaces"
      produces:
        - "application/json"
      responses:
        200:
          description: "All namespaces retrieved successfully"
          schema:
            $ref: "#/definitions/NamespaceResponse"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"

  /resources:
    get:
      tags:
        - "Logs"
      summary: "Get all resources in a namespace"
      operationId: "listResources"
      produces:
        - "application/json"
      parameters:
        - name: "namespace"
          in: "query"
          required: true
          type: "string"
          description: "Name of the namespace"
        - name: "resourceType"
          in: "query"
          required: false
          type: "string"
          description: "Type of the resource"
      responses:
        200:
          description: "All resources in the namespace retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourcesList"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"

  # /resources/{namespace}:
  #   get:
  #     tags:
  #       - "Logs"
  #     summary: "Get all resources in a namespace"
  #     operationId: "getResources"
  #     produces:
  #       - "application/json"
  #     parameters:
  #       - name: "namespace"
  #         in: "path"
  #         required: true
  #         type: "string"
  #         description: "Name of the namespace"
  #     responses:
  #       200:
  #         description: "All resources in the namespace retrieved successfully"
  #         schema:
  #           type: "array"
  #           items:
  #             $ref: "#/definitions/ResourcesList"
  #       401:
  #         description: "Unauthorized"
  #       403:
  #         description: "Forbidden"
  #       404:
  #         description: "Not Found"

  /resource:
    get:
      tags:
        - "Logs"
      summary: "Get all resources in a namespace"
      operationId: "getResource"
      produces:
        - "application/json"
      parameters:
        - name: "namespace"
          in: "query"
          required: true
          type: "string"
          description: "Name of the namespace"
        - name: "resourceType"
          in: "query"
          required: true
          type: "string"
          description: "Type of the resource"
        - name: "name"
          in: "query"
          required: true
          type: "string"
          description: "Name of the resource"
      responses:
        200:
          description: "Resource information retrieved successfully"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ResourceInfo"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"

  /logs/{namespace}:
    get:
      tags:
        - "Logs"
      summary: "Get all logs"
      operationId: "getLogs"
      produces:
        - "application/json"
      responses:
        200:
          description: "All logs retrieved successfully"
          schema:
            $ref: "#/definitions/LogResponse"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"

definitions:
  ResourceInfo:
    type: "object"
    properties:
      namespace:
        type: "string"
        description: "Namespace of the resource"
      resourceType:
        type: "string"
        description: "Type of the resource"
      name:
        type: "string"
        description: "Name of the resource"
      status:
        type: "string"
        description: "Status of the resource"
      information:
        type: "object"
        additionalProperties: true
        description: "Additional information about the resource"
    required:
      - namespace
      - resourceType
      - name
      - status

  NamespaceResponse:
    type: "object"
    properties:
      namespaces:
        type: "array"
        items:
          $ref: "#/definitions/NamespaceInList"
    required:
      - namespaces

  ResourcesList:
    type: "object"
    properties:
      namespace:
        type: "string"
        description: "Namespace of the resource"
      resources:
        type: "array"
        items:
          $ref: "#/definitions/ResourcesByType"
    required:
      - namespace
      - resources

  ResourcesByType:
    type: "object"
    properties:
      resourceType:
        type: "string"
        description: "Type of the resource"
        example: "pod"
      resources:
        type: "array"
        items:
          $ref: "#/definitions/ResourcesInList"
    required:
      - resourceType
      - resources

  ResourcesInList:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Name of the resource"
      informationPath:
        type: "string"
        description: "Api path to get information for the resource"
    required:
      - name
      - informationPath

  NamespaceInList:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Name of the namespace"
      resourcesPath:
        type: "string"
        description: "Api path to get resources for the namespace"
    required:
      - name
      - resourcesPath

  LogResponse:
    type: "object"
    properties:
      Logs:
        type: "array"
        items:
          $ref: "#/definitions/Logs"
    required:
      - LogResponse

  Logs:
    type: "object"
    properties:
      namespace:
        type: "string"
        description: "Namespace of the pod"
      pod:
        type: "string"
        description: "Name of the pod"
      status:
        type: "string"
        description: "Status of the pod"
      node:
        type: "string"
        description: "Node where the pod is running"
      logs:
        type: "string"
        description: "Logs of the pod"
    required:
      - namespace
      - pod
      - status
      - node
      - logs

  Response:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
    required:
      - token
      - message