swagger: "2.0"
info:
  version: "1.0.0"
  title: "API for kogger"
basePath: "/api"
tags:
  - name: "Logs"
    description: "Endpoints for logs"

paths:
  /logs:
    get:
      tags:
        - "Logs"
      summary: "Get all logs"
      operationId: "getLogs"
      produces:
        - "application/json"
      responses:
        200:
          description: "All logs retrieved successfully"
          schema:
            $ref: "#/definitions/LogResponse"
        401:
          description: "Unauthorized"
        403:
          description: "Forbidden"
        404:
          description: "Not Found"

definitions:
  LogResponse:
    type: "object"
    properties:
      Logs:
        type: "array"
        items:
          $ref: "#/definitions/Logs"
    required:
      - LogResponse

  Logs:
    type: "object"
    properties:
      namespace:
        type: "string"
        description: "Namespace of the pod"
      pod:
        type: "string"
        description: "Name of the pod"
      status:
        type: "string"
        description: "Status of the pod"
      node:
        type: "string"
        description: "Node where the pod is running"
      logs:
        type: "string"
        description: "Logs of the pod"
    required:
      - namespace
      - pod
      - status
      - node
      - logs

  Response:
    type: "object"
    properties:
      token:
        type: "string"
      message:
        type: "string"
    required:
      - token
      - message