/*
 * API for kogger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type Logs struct {

	// Namespace of the pod
	Namespace string `json:"namespace"`

	// Name of the pod
	Pod string `json:"pod"`

	// Status of the pod
	Status string `json:"status"`

	// Node where the pod is running
	Node string `json:"node"`

	// Logs of the pod
	Logs string `json:"logs"`
}
