/*
 * API for kogger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package models

type ResourcesInList struct {

	// Name of the resource
	Name string `json:"name"`

	// Api path to get information for the resource
	InformationPath string `json:"informationPath"`
}
